name: Eleventy Build
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout
        uses: actions/checkout@master

      - name: 🛠 Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --input site

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          state-name: ../.sync-state.json
          log-level: verbose
